### ISSUE TITLE
Hackthon 2019 I

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/meta#1]
TBD: Fill here

-----

TODO:
- [x] find topics for workshops and learning sessions

**Comment by Fohlen** [comment]
> wir haben heute im Plenum beschlossen dass ihr euch gerne für den Hackathon bei uns im Club abhalten dürft.
> Im Februar/März sind glaub ich noch alle Wochenenden frei so weit ich das sehen kann.
> Somit brauch es nur ein Wochenende wann ihr das machen wollt. 


CCC Freiburg announced today that they will host us and that we can choose any date in february or march that we would like.

I have created a doodle to fix a date, see https://doodle.com/poll/gbv4acgsxb5stfsw

Please do vote until January 16th, 6 PM CEST (one week from the initial announcement).
I will then check back with CCCFR to let them know our date.

Also tagging @inexorgame/members so all active members get a notification.

**Comment by Fohlen** [comment]
Closing the Doodle because it is very clear that the Hackathon will be on 1st of March.

Now all that is left to do is:

- [ ] communicate the date with Freiburg (@Fohlen)
- [ ] design a flyer to send to Freiburg (?)
- [ ] find accomodation (@Fohlen)
- [ ] suggest topics / timeline (?)
- [ ] announce Hackathon officially via blog post (?)

**Comment by Fohlen** [comment]
I have sent our flyer to Freiburg people. Thanks again @IAmNotHanni
